import type {Claim,Observation} from './schema';
import {EDITION} from './edition';
export const claims:Claim[]=[
{id:'edi-base',publisher:'Ethereum Decentralization Index',url:EDITION.repository+'/blob/'+EDITION.ediCommit+'/data/control-registry.json',title:'Canonical Base scope and settlement dependency',date:'2026-10-02',dateKind:'retrieved',state:'capability',subjects:['base','ethereum']},
{id:'edi-weth9',publisher:'Ethereum Decentralization Index',url:EDITION.repository+'/blob/'+EDITION.ediCommit+'/data/control-registry.json',title:'Canonical Ethereum WETH9 identity and backing',date:'2026-10-02',dateKind:'retrieved',state:'capability',subjects:['weth9','native-eth']},
{id:'uniswap-2020',publisher:'Uniswap Labs',url:'https://blog.uniswap.org/year-in-review',title:'Uniswap in 2020',date:'2020-12-31',state:'reported-adoption',subjects:['uniswap-v2']},
{id:'morpho-2024',publisher:'Morpho',url:'https://morpho.org/blog/morpho-secures-50m-in-funding-led-by-ribbit-capital/',title:'Morpho secures $50M in funding led by Ribbit Capital',date:'2024-08-01',state:'reported-adoption',subjects:['morpho-blue']},
{id:'coinbase-2026',publisher:'Coinbase',url:'https://www.coinbase.com/blog/uk-users-can-now-borrow-usdc-against-their-crypto-holdings',title:'UK users can now borrow USDC against their crypto holdings',date:'2026-04-20',state:'reported-adoption',subjects:['base','morpho-blue','usdc'],qualification:'Cumulative originations on Base as of 14 April 2026; not outstanding debt or L1 activity.'},
{id:'opensea-offers',publisher:'OpenSea',url:'https://docs.opensea.io/docs/collection-offers-and-advanced-trading',title:'Collection offers and advanced trading',date:'2026-10-02',dateKind:'retrieved',state:'capability',subjects:['weth9','seaport-v1.6']},
{id:'opensea-seaport',publisher:'OpenSea',url:'https://docs.opensea.io/docs/seaport',title:'Seaport documentation',date:'2026-10-02',dateKind:'retrieved',state:'capability',subjects:['weth9','seaport-v1.6']},
{id:'visa-2021',publisher:'Visa',url:'https://usa.visa.com/about-visa/newsroom/press-releases.releaseld.17821.html',title:'Visa becomes first major payments network to settle transactions in USD Coin',date:'2021-03-29',state:'pilot',subjects:['usdc','ethereum']},
{id:'visa-2026',publisher:'Visa',url:'https://investor.visa.com/news/news-details/2026/Visa-Accelerates-Stablecoin-Momentum-Adding-Five-Blockchains-for-Settlement/',title:'Visa accelerates stablecoin momentum',date:'2026-04-29',state:'reported-adoption',subjects:['usdc','ethereum'],qualification:'Nine-chain annualized run rate; no Ethereum-only amount is reported here.'},
{id:'buidl-launch',publisher:'Securitize',url:'https://investors.securitize.io/news/news-details/2024/BlackRock-Launches-Its-First-Tokenized-Fund-BUIDL-on-the-Ethereum-Network-03-20-2024/default.aspx',title:'BlackRock launches BUIDL on the Ethereum network',date:'2024-03-20',state:'live',subjects:['buidl']},
{id:'buidl-uniswapx',publisher:'Securitize',url:'https://investors.securitize.io/news/news-details/2026/Uniswap-Labs-and-Securitize-Collaborate-to-Unlock-Liquidity-Options-for-BlackRocks-BUIDL-02-11-2026/default.aspx',title:'Uniswap Labs and Securitize collaborate on BUIDL liquidity',date:'2026-02-11',state:'announced',subjects:['buidl'],qualification:'UniswapX RFQ for pre-qualified investors and approved counterparties; not a verified v4 pool.'},
{id:'permissioned-pools',publisher:'Uniswap Labs',url:'https://blog.uniswap.org/introducing-permissioned-pools-on-uniswap-v4',title:'Introducing Permissioned Pools on Uniswap v4',date:'2026-07-23',state:'capability',subjects:['uniswap-v4']}
];
export const observations:Observation[]=[
{id:'v2-flash-2020',subjectId:'uniswap-v2',metric:'Flash-swap volume',value:'4800000000',unit:'USD',measure:'flow',comparator:'eq',asOf:'2020-12-31',chainIds:[1],scope:'Uniswap v2 flash swaps since its May 2020 launch; first-party year-end report.',claimIds:['uniswap-2020']},
{id:'morpho-deposits-2024',subjectId:'morpho-blue',metric:'Reported deposits exceeded',value:'1700000000',unit:'USD',measure:'stock',comparator:'gt',asOf:'2024-08-01',chainIds:[1],scope:'Morpho Blue on Ethereum, six months after launch. Historical deposits, not current TVL.',claimIds:['morpho-2024']},
{id:'coinbase-originations-2026',subjectId:'base',metric:'Reported cumulative loan originations exceeded',value:'2170000000',unit:'USDC',measure:'flow',comparator:'gt',asOf:'2026-04-14',chainIds:[8453],scope:'Coinbase borrowing through Morpho on Base; cumulative originations through 14 April 2026, not outstanding debt.',claimIds:['coinbase-2026']}
];
