export type Locale='en'|'es'|'pt-BR'|'fr'|'de'|'zh-CN'|'ja'|'ko';
export const LOCALES:Locale[]=['en','es','pt-BR','fr','de','zh-CN','ja','ko'];
export const LANGUAGE_NAMES:Record<Locale,string>={en:'English',es:'Español','pt-BR':'Português',fr:'Français',de:'Deutsch','zh-CN':'简体中文',ja:'日本語',ko:'한국어'};
export type Role='money'|'exchange'|'lending'|'settlement'|'network'|'staking'|'assets'|'infrastructure';
export type EvidenceState='capability'|'announced'|'pilot'|'live'|'reported-adoption';
export interface Profile{id:string;role:Role;title:string;summary:string;enables:string;boundary:string;storyIds:string[];tags:string[];global?:boolean}
export interface Claim{id:string;publisher:string;url:string;title:string;date:string;dateKind?:'retrieved';state:EvidenceState;subjects:string[];qualification?:string}
export interface Relationship{id:string;from:string;to:string;type:'settles-on'|'issues'|'interface-to'|'integrates-with'|'collateral-for'|'economic-reference';state:EvidenceState;claimIds:string[];storyIds:string[];chainIds?:number[]}
export interface Observation{id:string;subjectId:string;metric:string;value:string;unit:string;measure:'stock'|'flow';comparator:'eq'|'gt';asOf:string;interval?:{start:string;end:string};chainIds:number[];scope:string;claimIds:string[]}
export interface Story{id:string;title:string;subtitle:string;collection:('d0'|'global-economy')[];objectIds:string[];claimIds:string[];observationIds:string[];relationshipIds:string[];state:EvidenceState;sections:{heading:string;body:string}[];connection:{from:string;relation:string;to:string}[]}
export interface Editorial{profiles:Profile[];stories:Story[];methodology:{title:string;body:string}[];collectionDescriptions:{d0:string;'global-economy':string}}
export type UI=Record<string,string>;
