"use client";
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {Choice} from './choice';
import {Badge} from './badge';
import {catalog,slugFor,NETWORKS} from '@/lib/catalog';
import {utcToday,evaluationDay} from '@/lib/edition';
import {date} from '@/lib/format';
import type {Locale,Profile,UI} from '@/lib/schema';
export function Comparison({ids,locale,t,profiles,asOf}:{ids:string[];locale:Locale;t:UI;profiles:Profile[];asOf:string}){
 const [day,setDay]=useState(asOf);const [pair,setPair]=useState([ids[0],ids[1]]);
 useEffect(()=>{const update=()=>setDay(evaluationDay(utcToday(),asOf));update();document.addEventListener('visibilitychange',update);const timer=setInterval(update,60000);const readPair=()=>{const p=new URLSearchParams(location.search);const a=p.get('left'),b=p.get('right');setPair(a&&b&&ids.includes(a)&&ids.includes(b)&&a!==b?[a,b]:[ids[0],ids[1]])};readPair();window.addEventListener('popstate',readPair);window.addEventListener('pageshow',update);return()=>{document.removeEventListener('visibilitychange',update);window.removeEventListener('popstate',readPair);window.removeEventListener('pageshow',update);clearInterval(timer)}},[ids]);
 const sequence=[...pair,...ids.filter(id=>!pair.includes(id))];
 const rows=catalog(profiles,day).filter(r=>ids.includes(r.id)).sort((a,b)=>sequence.indexOf(a.id)-sequence.indexOf(b.id));
 function setVisible(index:number,id:string){let next=[...pair];if(next[1-index]===id)next[1-index]=next[index];next[index]=id;setPair(next);const p=new URLSearchParams(location.search);p.set('left',next[0]);p.set('right',next[1]);history.pushState({...history.state},'','?'+p);}
 if(rows.length===0)return <div className="empty-state"><p>{t.chooseObjects}</p><Link className="button" href={'/'+locale}>{t.directory}</Link></div>;
 const fields=[['role',r=>t[r.role==='network'?'networkRole':r.role]],['mechanism',r=><><Badge assessment={r.assessment} t={t}/><p>{r.assessment.effectiveLevel!=null?t['ediTierDef_'+r.assessment.effectiveLevel]:t.unresolved}</p></>],['network',r=>r.networks.map(id=>id==='1'?t.mainnet:NETWORKS.find(([key])=>key===id)?.[1]||id).join(', ')||t.unspecified],['scope',r=><>{r.profile?.boundary||t.mechanismScope}<details><summary>{t.originalResearch}</summary><p>{r.scope}</p></details></>],['controls',r=>r.profile?.boundary||<span>{r.assessment.effectiveLevel!=null?t['ediTierDef_'+r.assessment.effectiveLevel]:t.unresolved}</span>],['position',r=><>{r.positionReview?<Badge assessment={r.position} t={t}/>:<strong>{t.noPosition}</strong>}<p>{t.positionLimit}</p></>],['researchDate',r=>date(r.reviewedAt,locale)],['nextReview',r=>r.timing.permanent?t.permanent:date(r.timing.dueAt!,locale)],['identity',r=><><code>{r.id}</code>{Object.entries(r.addresses).map(([chain,address])=><p key={chain} className="small break-all">{chain}: {address}</p>)}</>]] as [string,(r:typeof rows[number])=>React.ReactNode][];
 return <><div className="pair-controls"><p>{t.selectPair}</p>{rows.length>1&&[0,1].map(i=><Choice key={i} label={t[i===0?'leftObject':'rightObject']} value={pair[i]} options={rows.map(r=>[r.id,r.name])} onChange={v=>setVisible(i,v)}/>)}</div><div className="comparison-grid" style={{'--columns':rows.length} as React.CSSProperties}><div className="compare-label"/>{rows.map(r=><div key={r.id} className={'comparison-head '+(!pair.includes(r.id)?'pair-hidden':'')}><Link href={`/${locale}/objects/${slugFor(r.id)}`}>{r.name}</Link><p>{r.profile?.summary||t.basic}</p></div>)}{fields.map(([field,render])=><div className="compare-field" key={field}><div className="compare-label">{t[field]}</div>{rows.map(r=><div key={r.id} data-object={r.name} className={'comparison-cell '+(!pair.includes(r.id)?'pair-hidden':'')}>{render(r)}</div>)}</div>)}</div><p className="small muted">{t.evaluated} {date(day,locale)}</p></>;
}
