import Link from 'next/link';
import {safeEvidenceUrl} from '@/vendor/edi/dist/core/index.js';
import {claims,observations} from '@/lib/evidence';
import {date,amount} from '@/lib/i18n';
import type {Locale,Story,UI} from '@/lib/schema';
export function StoryCard({story:s,locale,t,index=0}:{story:Story;locale:Locale;t:UI;index?:number}){return <article className={'story-card story-color-'+index%3}><div className="story-card-meta"><span>{s.collection.map(c=>t[c==='d0'?'d0':'globalEconomy']).join(' / ')}</span><span>0{index+1}</span></div><h2><Link href={`/${locale}/stories/${s.id}`}>{s.title}</Link></h2><p>{s.subtitle}</p><div className="story-card-foot"><span>{t[s.state]}</span><Link className="underlined" href={`/${locale}/stories/${s.id}`}>{t.readStory}</Link></div></article>}
export function Sources({ids,locale,t}:{ids:string[];locale:Locale;t:UI}){return <ol className="source-list">{ids.map(id=>claims.find(c=>c.id===id)).filter(c=>!!c).map(c=><li key={c.id}><a href={safeEvidenceUrl(c.url)||undefined} rel="noopener noreferrer">{c.title}</a><div className="small muted">{c.publisher} · {c.dateKind==='retrieved'?t.retrieved+': ':''}{date(c.date,locale)} · {t[c.state]}</div></li>)}</ol>}
export function Observations({ids,locale,t}:{ids:string[];locale:Locale;t:UI}){const values=observations.filter(o=>ids.includes(o.id));if(!values.length)return <p className="muted">{t.noObservations}</p>;return <div className="observations">{values.map(o=><figure key={o.id} className="observation"><span className="eyebrow">{t.historical}</span><strong className="observation-value">{o.comparator==='gt'?'> ':''}{amount(o.value,o.unit,locale)}</strong><figcaption><strong>{t['metric_'+o.id]||o.metric}</strong><p>{t['scope_'+o.id]||o.scope}</p><div className="small">{o.chainIds[0]===1?t.mainnet:'Base'} · {date(o.asOf,locale)}</div><a className="underlined small" href={safeEvidenceUrl(claims.find(c=>c.id===o.claimIds[0])!.url)||undefined}>{t.source}: {claims.find(c=>c.id===o.claimIds[0])!.publisher}</a></figcaption></figure>)}</div>}
export function Connections({story:s,t}:{story:Story;t:UI}){return <figure className="connections"><figcaption className="eyebrow">{t.relationship}</figcaption><ol>{s.connection.map((edge,i)=><li key={i}><strong>{edge.from}</strong><span className="connection-verb">{edge.relation}</span><strong>{edge.to}</strong></li>)}</ol><p className="small muted">{t.contextCoverage}</p></figure>}
